### ISSUE TITLE
[Bounty] Custom Widget for OWM

### ISSUE THREAD

**Issue by AngelosF** [AngelosF/org.openhab.ui.habpanel#1]
Scope: To create a custom widget with navigation to be used with the latest [OpenWeatherMap binding](https://community.openhab.org/t/announcing-openweathermap-binding-for-eclipse-smarthome-openhab/46420)
(if technically possible on Angular.js with bootstrap components)

Widget Source code will be uploaded on github and made available to all as open source.

Description:
Develop a custom widget under openHAB2’s HABPanel in AngularJS to display Weather Forecast info already collected in OH2 Items.

A rough layout is attached

Some examples here:
a) https://community.openhab.org/t/template-widget-tutorial-examples-make-your-own-widget/14211
b) https://community.openhab.org/t/weather-underground-widget-with-forecast/40260
c) http://demo.openhab.org:8080/habpanel/index.html#/view/weather-astro

![2018112502 habpanel_widget_layout](https://user-images.githubusercontent.com/25465966/48977265-e2c7a080-f09f-11e8-9267-4ee6d7069b11.png)

**Comment by AngelosF** [comment]
Closing due to no interest from developers

**Comment by BasvanH** [comment]
I'm willing to build it, I already rebuild my existing widget to OWM: https://github.com/BasvanH/habpanel-widget-openweathermap

Do you want it to use the free or paid forecast?
